"use client";

import Link from "next/link";
import { AddToPlan } from "./SavedSuppliers";
import ServiceCategories from "./ServiceCategories";
import { getVendorCategory, getVendorCategoryFromHash, vendorCategories } from "./vendorCategories";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { supabase, vendorDirectoryKey, vendorDirectoryUrl } from "./supabase";

type Vendor = { id:string; business_name:string; category:string; description:string; phone:string; website:string; town:string; coverage_areas:string; services:string; email:string; };
type EnquiryDraft = { vendorId:string; vendorName:string; vendorEmail:string; customerName:string; customerEmail:string; subject:string; eventDate:string; eventLocation:string; message:string; };
type VendorOverride = Partial<Omit<Vendor,"id">> & { external_id:string; is_hidden:boolean; listing_status:"pending"|"approved"|"suspended"; };
const PAGE_SIZE=1000; const ENQUIRY_DRAFT_KEY="just-celebrate-enquiry-draft";

export default function VendorDirectory(){
 const router=useRouter(); const [vendors,setVendors]=useState<Vendor[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(""); const [category,setCategory]=useState(""); const [location,setLocation]=useState(""); const [enquiriesOnly,setEnquiriesOnly]=useState(false); const [visibleCount,setVisibleCount]=useState(12); const [selectedVendor,setSelectedVendor]=useState<Vendor|null>(null); const [submitting,setSubmitting]=useState(false); const [formMessage,setFormMessage]=useState(""); const [customerName,setCustomerName]=useState(""); const [customerEmail,setCustomerEmail]=useState(""); const [subject,setSubject]=useState(""); const [eventDate,setEventDate]=useState(""); const [eventLocation,setEventLocation]=useState(""); const [enquiryMessage,setEnquiryMessage]=useState("");
 useEffect(()=>{async function loadVendors(){try{const allVendors:Vendor[]=[];for(let offset=0;;offset+=PAGE_SIZE){const response=await fetch(`${vendorDirectoryUrl}/rest/v1/vendor_profiles?status=eq.approved&select=id,business_name,category,description,phone,website,town,coverage_areas,services,email&order=business_name.asc&offset=${offset}&limit=${PAGE_SIZE}`,{cache:"no-store",headers:{apikey:vendorDirectoryKey,Authorization:`Bearer ${vendorDirectoryKey}`}});if(!response.ok)throw new Error("Could not load vendors");const page=await response.json() as Vendor[];allVendors.push(...page);if(page.length<PAGE_SIZE)break;}const {data:overrides,error:overrideError}=await supabase.from("vendor_listing_overrides").select("external_id,business_name,category,description,phone,website,town,coverage_areas,services,email,is_hidden,listing_status");if(overrideError)throw overrideError;const overrideMap=new Map(((overrides||[]) as VendorOverride[]).map(i=>[i.external_id,i]));const sourceIds=new Set(allVendors.map(v=>v.id));const manualVendors=((overrides||[]) as VendorOverride[]).filter(i=>!sourceIds.has(i.external_id)).map(({external_id,is_hidden,listing_status,...vendor})=>({id:external_id,business_name:vendor.business_name||"Managed vendor",category:vendor.category||"Other",description:vendor.description||"",phone:vendor.phone||"",website:vendor.website||"",town:vendor.town||"",coverage_areas:vendor.coverage_areas||"",services:vendor.services||"",email:vendor.email||"",is_hidden,listing_status}));setVendors([...manualVendors,...allVendors].map(v=>{const o=overrideMap.get(v.id);if(!o)return v;return {...v,...Object.fromEntries(Object.entries(o).filter(([k,val])=>!["external_id","is_hidden","listing_status"].includes(k)&&val!==null)),is_hidden:o.is_hidden,listing_status:o.listing_status} as Vendor&{is_hidden?:boolean;listing_status?:string}}).filter(v=>{const m=v as Vendor&{is_hidden?:boolean;listing_status?:string};return !m.is_hidden&&m.listing_status!=="suspended"&&m.listing_status!=="pending"}));}catch{setError("We couldn't load vendors just now. Please try again shortly.");}finally{setLoading(false)}}loadVendors()},[]);
 useEffect(()=>{async function c(){if(!localStorage.getItem(ENQUIRY_DRAFT_KEY))return;const {data:{user}}=await supabase.auth.getUser();if(user)router.push("/complete-enquiry")}void c();const {data:l}=supabase.auth.onAuthStateChange(()=>window.setTimeout(()=>void c(),0));return()=>l.subscription.unsubscribe()},[router]);
 useEffect(()=>{function openLinkedCategory(){const linkedCategory=getVendorCategoryFromHash(window.location.hash);if(!linkedCategory)return;setCategory(linkedCategory);setLocation("");setEnquiriesOnly(false);setVisibleCount(12)}openLinkedCategory();window.addEventListener("hashchange",openLinkedCategory);return()=>window.removeEventListener("hashchange",openLinkedCategory)},[]);
 const categories=useMemo(()=>{const counts=new Map<string,number>();for(const vendor of vendors){const name=getVendorCategory(vendor.category);counts.set(name,(counts.get(name)||0)+1)}return vendorCategories.map(group=>({...group,count:counts.get(group.name)||0})).filter(group=>group.count>0)},[vendors]);
 function selectCategory(value:string){setCategory(value);setLocation("");setEnquiriesOnly(false);setVisibleCount(12)}
 const filtered=useMemo(()=>{const q=location.trim().toLowerCase();return vendors.filter(v=>getVendorCategory(v.category)===category&&(!q||(v.town||"").toLowerCase().includes(q)||(v.coverage_areas||"").toLowerCase().includes(q))&&(!enquiriesOnly||Boolean(v.email?.trim())))},[vendors,category,location,enquiriesOnly]);
 async function handleEnquiry(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selectedVendor?.email)return;setSubmitting(true);setFormMessage("");const draft:EnquiryDraft={vendorId:selectedVendor.id,vendorName:selectedVendor.business_name,vendorEmail:selectedVendor.email.trim(),customerName:customerName.trim(),customerEmail:customerEmail.trim().toLowerCase(),subject:subject.trim(),eventDate,eventLocation:eventLocation.trim(),message:enquiryMessage.trim()};localStorage.setItem(ENQUIRY_DRAFT_KEY,JSON.stringify(draft));const {data:{user}}=await supabase.auth.getUser();if(user?.email?.toLowerCase()===draft.customerEmail){router.push("/complete-enquiry");return}const {error:signInError}=await supabase.auth.signInWithOtp({email:draft.customerEmail,options:{emailRedirectTo:window.location.origin,shouldCreateUser:true,data:{display_name:draft.customerName,account_type:"customer"}}});if(signInError){setFormMessage("We couldn't send your secure confirmation link. Please try again.");setSubmitting(false);return}setFormMessage("Check your email and click the secure link to send your enquiry. Your message will then appear in your private inbox.");setSubmitting(false)}
 if(!category)return <section id="vendors" className="bg-[#f8f4ec] py-14 sm:py-16"><div className="mx-auto max-w-7xl px-5 sm:px-6 lg:px-8"><ServiceCategories categories={categories} loading={loading} onSelect={selectCategory}/>{error&&<p className="mt-6 rounded-2xl bg-white p-5">{error}</p>}</div></section>;
 return <section id="vendors" className="min-h-screen bg-[#f8f4ec] py-10 sm:py-14"><div className="mx-auto max-w-6xl px-5 sm:px-6 lg:px-8">
 <button type="button" onClick={()=>selectCategory("")} className="mb-6 text-sm font-bold text-[#063d39]">← Choose another service</button>
 <div className="overflow-hidden rounded-[2rem] border border-[#e5ded1] bg-white shadow-[0_18px_50px_rgba(6,61,57,.06)]"><div className="border-b border-[#e9e4da] bg-[#f3f5ec] p-6 sm:p-8"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-[#839070]">Find your supplier</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-[#082f2c] sm:text-4xl">{category}</h1><p className="mt-2 text-[#66756f]">Choose the right business for your celebration and save it straight to My Planning Portal.</p></div><div className="rounded-full bg-white px-4 py-2 text-sm font-semibold text-[#60706a]">{loading?"Finding vendors…":`${filtered.length} vendors`}</div></div>
 <div className="mt-6 grid gap-3 md:grid-cols-[1fr_1fr_auto]"><select aria-label="Service category" value={category} onChange={e=>selectCategory(e.target.value)} className="rounded-2xl border border-[#dfe3d7] bg-white px-4 py-3 text-[#173d38]">{categories.map(i=><option key={i.name}>{i.name}</option>)}</select><input aria-label="Filter by location" value={location} onChange={e=>{setLocation(e.target.value);setVisibleCount(12)}} placeholder="Your area, e.g. London" className="rounded-2xl border border-[#dfe3d7] bg-white px-4 py-3 text-[#173d38]"/><button onClick={()=>{setLocation("");setEnquiriesOnly(false)}} className="rounded-2xl border border-[#dfe3d7] bg-white px-5 py-3 text-sm font-bold text-[#063d39]">Clear</button></div></div>
 <div className="p-5 sm:p-8"><label className="mb-6 flex w-fit items-center gap-2 text-sm font-semibold text-[#60706a]"><input type="checkbox" checked={enquiriesOnly} onChange={e=>setEnquiriesOnly(e.target.checked)} className="size-4 accent-[#063d39]"/>Only show vendors accepting enquiries</label>{!error&&!loading&&filtered.length===0&&<div className="rounded-2xl bg-[#f7f7f1] p-8 text-center text-[#60706a]">No matching vendors yet. Try another area or clear the location filter.</div>}
 <div className="space-y-4">{filtered.slice(0,visibleCount).map(v=><article key={v.id} className="rounded-3xl border border-[#e8e4db] bg-white p-5 transition hover:border-[#cbd4c1] hover:shadow-[0_12px_30px_rgba(6,61,57,.07)] sm:p-6"><div className="grid gap-5 lg:grid-cols-[1fr_190px]"><div><div className="flex flex-wrap items-center gap-2"><span className="rounded-full bg-[#eef3e6] px-3 py-1 text-xs font-bold text-[#56704d]">{v.category}</span>{v.email&&<span className="rounded-full bg-[#fff1e7] px-3 py-1 text-xs font-bold text-[#c75b21]">Enquiries open</span>}</div><h2 className="mt-3 text-2xl font-semibold text-[#082f2c]">{v.business_name}</h2>{v.town&&<p className="mt-1 text-sm font-medium text-[#75807c]">⌖ {v.town}</p>}{v.description&&<p className="mt-3 max-w-3xl text-sm leading-6 text-[#65716d]">{v.description}</p>}<div className="mt-4 flex flex-wrap gap-4 text-sm font-bold"><Link href={`/vendor?name=${encodeURIComponent(v.business_name)}`} className="text-[#063d39] underline decoration-[#b8c4b2] underline-offset-4">View profile</Link>{v.website&&<a href={v.website} target="_blank" rel="noreferrer" className="text-[#063d39] underline decoration-[#b8c4b2] underline-offset-4">Website</a>}{v.phone&&<a href={`tel:${v.phone.replace(/\s/g,"")}`} className="text-[#063d39]">{v.phone}</a>}</div></div><div className="flex flex-col justify-center"><AddToPlan vendor={v}/>{v.email?<button onClick={()=>{setSelectedVendor(v);setSubject(`Enquiry for ${v.business_name}`);setFormMessage("")}} className="mt-3 rounded-xl border border-[#063d39] px-4 py-3 text-sm font-bold text-[#063d39]">Send enquiry</button>:<p className="mt-3 text-center text-xs text-[#8a938f]">Enquiries opening soon</p>}</div></div></article>)}</div>{visibleCount<filtered.length&&<button onClick={()=>setVisibleCount(c=>c+12)} className="mt-6 w-full rounded-2xl bg-[#f0f2e9] px-5 py-4 font-bold text-[#063d39]">View more {category.toLowerCase()} →</button>}</div></div></div>
 {selectedVendor&&<div className="fixed inset-0 z-[100] flex items-center justify-center overflow-y-auto bg-[#082f2c]/50 px-4 py-8"><div className="relative w-full max-w-2xl rounded-[2rem] bg-[#fffdf9] p-6 shadow-2xl sm:p-8"><button type="button" onClick={()=>setSelectedVendor(null)} className="absolute right-6 top-5 text-2xl text-[#063d39]">×</button><p className="text-xs font-bold uppercase tracking-[.22em] text-[#c75b21]">Private enquiry</p><h2 className="mt-2 text-3xl font-semibold text-[#082f2c]">Contact {selectedVendor.business_name}</h2><form onSubmit={handleEnquiry} className="mt-6 grid gap-4 sm:grid-cols-2"><input value={customerName} onChange={e=>setCustomerName(e.target.value)} placeholder="Your name" required className="rounded-xl border px-4 py-3"/><input type="email" value={customerEmail} onChange={e=>setCustomerEmail(e.target.value)} placeholder="Your email" required className="rounded-xl border px-4 py-3"/><input value={subject} onChange={e=>setSubject(e.target.value)} placeholder="What do you need?" required className="rounded-xl border px-4 py-3 sm:col-span-2"/><input type="date" value={eventDate} onChange={e=>setEventDate(e.target.value)} className="rounded-xl border px-4 py-3"/><input value={eventLocation} onChange={e=>setEventLocation(e.target.value)} placeholder="Event location" className="rounded-xl border px-4 py-3"/><textarea value={enquiryMessage} onChange={e=>setEnquiryMessage(e.target.value)} placeholder="Tell the vendor what you need." required rows={5} className="rounded-xl border px-4 py-3 sm:col-span-2"/><button type="submit" disabled={submitting} className="rounded-xl bg-[#063d39] px-5 py-3 font-semibold text-white sm:col-span-2">{submitting?"Preparing secure enquiry…":"Confirm and send enquiry"}</button></form>{formMessage&&<div className="mt-5 rounded-xl bg-[#eef3e6] p-4 text-sm">{formMessage}</div>}</div></div>}</section>;
}
